(() => {
  const config = window.RKH_CONFIG || {};
  const base = String(config.apiBaseUrl || '').replace(/\/$/, '');
  const endpoints = config.endpoints || {};
  const state = { runs: [], run: null, results: [], activeGrade: 'All' };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const apiUrl = (path, query = {}) => { const url = new URL(`${base}${path}`); Object.entries(query).forEach(([key, value]) => value != null && url.searchParams.set(key, value)); return url.toString(); };
  const statusClass = (status) => String(status || '').toLowerCase() === 'completed' ? 'completed' : String(status || '').toLowerCase() === 'failed' ? 'failed' : 'processing';
  const count = (run, key) => Number(key === 'total' ? (run?.total_rows ?? run?.total ?? 0) : (run?.[`${key}_count`] ?? run?.[key] ?? 0));

  async function request(path, options = {}, query = {}) {
    if (!base) throw new Error('API base URL is not configured.');
    const response = await fetch(apiUrl(path, query), options);
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error_message || body.message || `API request failed (${response.status})`);
    return body;
  }
  function setStep(number) { document.querySelectorAll('.step').forEach((step) => { const value = Number(step.dataset.step); step.classList.toggle('active', value === number); step.classList.toggle('done', value < number); }); }
  function showError(message) { $('upload-error').textContent = message; $('upload-error').classList.remove('hidden'); }
  function clearError() { $('upload-error').classList.add('hidden'); $('upload-error').textContent = ''; }
  function progress(title, status, message, value) { const complete = value >= 100 || status === 'Completed' || status === 'Failed'; $('progress-area').classList.remove('hidden'); $('progress-area').classList.toggle('complete', complete); $('progress-title').textContent = title; $('progress-status').textContent = status; $('progress-message').textContent = message; $('progress-bar').style.width = `${Math.max(0, Math.min(100, value))}%`; }

  function renderRuns() {
    $('report-count').textContent = state.runs.length;
    if (!state.runs.length) { $('report-list').innerHTML = '<div class="empty-state">No reports have been loaded yet.</div>'; return; }
    $('report-list').innerHTML = state.runs.map((run) => `<div class="report-row"><div><strong>${esc(run.filename || run.file_name || run.run_id)}</strong><span class="muted">${esc(run.source || 'DASHBOARD_UPLOAD')} · ${esc(run.created_at || '')}</span></div><div><span class="status ${statusClass(run.status)}">${esc(run.status || 'UNKNOWN')}</span><span class="muted">${count(run, 'total')} work orders · ${count(run, 'red')} Red</span></div><div class="muted">Green ${count(run, 'green')} · Yellow ${count(run, 'yellow')} · Amber ${count(run, 'amber')}</div><button class="button subtle open-run" data-run-id="${esc(run.run_id)}">View</button></div>`).join('');
    document.querySelectorAll('.open-run').forEach((button) => button.addEventListener('click', () => loadRun(button.dataset.runId)));
  }
  function normalizeRun(payload) { return payload.run || payload.result || payload; }
  function normalizeResults(payload) { return payload.results || payload.rows || payload.data || []; }
  function renderDetail() {
    const run = state.run; if (!run) return;
    $('detail-title').textContent = run.filename || run.file_name || run.run_id;
    $('detail-meta').textContent = [run.run_id, run.source, run.created_at, run.rule_version, `${run.mapping_confidence ?? '—'}% mapping confidence`].filter(Boolean).join(' · ');
    ['green', 'yellow', 'amber', 'red'].forEach((grade) => { $(`count-${grade}`).textContent = count(run, grade); });
    renderResults();
  }
  function renderResults() {
    const query = $('search').value.trim().toLowerCase(); const type = $('type-filter').value; const grade = state.activeGrade !== 'All' ? state.activeGrade : $('grade-filter').value;
    const rows = state.results.filter((row) => { const blob = [row.wo_number, row.work_type, row.status, row.location, row.category, row.action, row.original_problem, row.worklog, ...(row.keyword_hits || []), ...(row.matched_rule_ids || [])].join(' ').toLowerCase(); return (!query || blob.includes(query)) && (type === 'All' || row.work_type === type) && (grade === 'All' || row.grade === grade); });
    $('results-empty').classList.toggle('hidden', rows.length > 0); $('results-table').innerHTML = rows.map((row) => `<tr><td><strong>${esc(row.wo_number)}</strong></td><td>${esc(row.work_type)}</td><td>${esc(row.status || '—')}</td><td>${esc(row.location || '—')}</td><td>${esc(row.category || '—')}</td><td><span class="grade ${esc(row.grade)}">${esc(row.grade)}</span></td><td>${esc(row.action || '—')}</td><td><button class="button subtle row-action view-wo" data-row="${Number(row.row_number)}">View</button></td></tr>`).join('');
    document.querySelectorAll('.view-wo').forEach((button) => button.addEventListener('click', () => showWorkOrder(Number(button.dataset.row))));
  }
  function showWorkOrder(rowNumber) {
    const row = state.results.find((item) => Number(item.row_number) === rowNumber); if (!row) return;
    $('wo-title').textContent = `${row.wo_number} · ${row.grade}`; $('wo-meta').textContent = [row.work_type, row.status, row.location, row.contractor].filter(Boolean).join(' · '); $('wo-problem').textContent = row.original_problem || 'Not mapped / not available'; $('wo-worklog').textContent = row.worklog || 'Not available'; $('wo-rules').textContent = (row.matched_rule_ids || []).join(', ') || 'No exception rule'; $('wo-keywords').textContent = (row.keyword_hits || []).join(', ') || 'No keyword hits'; $('wo-action').textContent = row.action || '—'; $('wo-checks').textContent = [...(row.reasons || []), ...(row.warnings || []), row.relation?.state ? `Relationship: ${row.relation.state}` : ''].filter(Boolean).join('\n') || 'No additional checks.'; $('wo-detail').classList.remove('hidden'); $('wo-detail').scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }
  function exportResults() {
    if (!state.results.length) return; const fields = ['wo_number', 'work_type', 'status', 'location', 'grade', 'category', 'action', 'reason_code', 'keyword_hits', 'matched_rule_ids', 'reasons', 'warnings', 'original_problem', 'worklog']; const quote = (value) => `"${String(Array.isArray(value) ? value.join(' | ') : value ?? '').replaceAll('"', '""')}"`; const lines = [fields.join(',')]; state.results.forEach((row) => lines.push(fields.map((field) => quote(row[field])).join(','))); const blob = new Blob(['\ufeff' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `RKH_Assurance_${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href);
  }
  async function loadRuns(retry = true) { $('report-list').innerHTML = '<div class="loading-state"><span class="loading-spinner" aria-hidden="true"></span><span>Loading recent reports...</span></div>'; try { state.runs = (await request(endpoints.listRuns)).runs || []; $('connection-note').textContent = ''; renderRuns(); if (!state.runs.length && retry) setTimeout(() => loadRuns(false), 700); } catch (error) { $('connection-note').textContent = `Backend connection unavailable: ${error.message}.`; renderRuns(); } }
  async function loadRun(runId) { try { const runPayload = await request(endpoints.getRun, {}, { run_id: runId }); state.run = normalizeRun(runPayload); state.results = normalizeResults(await request(endpoints.getResults, {}, { run_id: runId })); $('reports-view').classList.add('hidden'); $('detail-view').classList.remove('hidden'); setStep(state.run.status === 'COMPLETED' ? 4 : 3); renderDetail(); } catch (error) { showError(error.message); } }
  async function pollRun(runId, started) { while (Date.now() - started < (config.pollTimeoutMs || 600000)) { const payload = normalizeRun(await request(endpoints.getRun, {}, { run_id: runId })); state.run = payload; const status = String(payload.status || '').toUpperCase(); if (status === 'COMPLETED') { progress('Report ready', 'Completed', 'Analysis completed. Opening the review.', 100); setStep(4); state.results = normalizeResults(await request(endpoints.getResults, {}, { run_id: runId })); state.runs = [payload, ...state.runs.filter((run) => run.run_id !== runId)]; renderRuns(); $('reports-view').classList.add('hidden'); $('detail-view').classList.remove('hidden'); renderDetail(); return; } if (status === 'FAILED' || status === 'QUARANTINED') throw new Error(payload.error_message || `Run ${status.toLowerCase()}.`); const analyzing = status === 'ANALYZING'; progress(analyzing ? 'Analyzing your report' : 'Preparing your report', status, analyzing ? 'Applying the PM/CM assurance rules...' : 'Saving the source and preparing work-order records...', analyzing ? 72 : 40); setStep(analyzing ? 3 : 2); await new Promise((resolve) => setTimeout(resolve, config.pollMs || 1500)); } throw new Error('The run did not finish before the polling timeout. Check Recent reports.'); }
  async function upload(file) { clearError(); if (!file) return; const extension = file.name.toLowerCase().split('.').pop(); if (!['csv', 'xlsx', 'xls'].includes(extension)) { showError('Choose a CSV or XLSX report.'); return; } setStep(1); progress('Uploading your report', 'Uploading', 'Sending the source file to n8n...', 18); const form = new FormData(); form.append('data', file, file.name); try { const payload = await request(endpoints.upload, { method: 'POST', body: form }); const runId = payload.run_id || payload.run?.run_id; if (!runId) throw new Error('The upload response did not include a Run ID.'); progress('Preparing your report', 'Received', `Run ${runId} created.`, 32); await pollRun(runId, Date.now()); } catch (error) { progress('Report run needs attention', 'Failed', error.message, 100); setStep(1); showError(error.message); await loadRuns(); } }
  $('choose-file').addEventListener('click', () => $('file-input').click()); $('file-input').addEventListener('change', () => upload($('file-input').files[0])); $('drop-zone').addEventListener('click', () => $('file-input').click()); $('drop-zone').addEventListener('dragover', (event) => { event.preventDefault(); $('drop-zone').classList.add('active'); }); $('drop-zone').addEventListener('dragleave', () => $('drop-zone').classList.remove('active')); $('drop-zone').addEventListener('drop', (event) => { event.preventDefault(); $('drop-zone').classList.remove('active'); upload(event.dataTransfer.files[0]); }); $('refresh-runs').addEventListener('click', loadRuns); $('back-to-reports').addEventListener('click', () => { $('detail-view').classList.add('hidden'); $('reports-view').classList.remove('hidden'); setStep(1); }); $('detail-export').addEventListener('click', exportResults); $('close-wo').addEventListener('click', () => $('wo-detail').classList.add('hidden')); $('search').addEventListener('input', renderResults); $('type-filter').addEventListener('change', renderResults); $('grade-filter').addEventListener('change', () => { state.activeGrade = 'All'; renderResults(); }); $('reset-filters').addEventListener('click', () => { $('search').value = ''; $('type-filter').value = 'All'; $('grade-filter').value = 'All'; state.activeGrade = 'All'; renderResults(); }); document.querySelectorAll('.summary-card').forEach((card) => card.addEventListener('click', () => { state.activeGrade = state.activeGrade === card.dataset.filter ? 'All' : card.dataset.filter; $('grade-filter').value = 'All'; renderResults(); }));
  loadRuns();
})();
